// Copyright (c) 2017-2022, University of Tennessee. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
// This program is free software: you can redistribute it and/or modify it under
// the terms of the BSD 3-Clause license. See the accompanying LICENSE file.

#ifndef BLAS_DEFINES_H
#define BLAS_DEFINES_H

// auto-generated by: ./configure.py CXX=g++-12
//  
// host: 
//
// Definitions for:
// CXX   = g++-12
//         
// LIBS  = -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lm
//         

#define BLAS_FORTRAN_ADD_
#define BLAS_COMPLEX_RETURN_ARGUMENT
#define BLAS_HAVE_MKL
#define BLAS_HAVE_CBLAS
#define BLAS_HAVE_LAPACK


#endif        //  #ifndef BLAS_DEFINES_H
